import { ProjectType } from '@/types/project';

export const projects: ProjectType[] = [
    {
        category: 'official',
        name: 'xPortal',
        url: 'https://xportal.com',
        icon: 'xportal.svg',
    },
    {
        category: 'official',
        name: 'xExchange',
        url: 'https://xexchange.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'xLaunchpad',
        url: 'https://xlaunchpad.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'xDevHub',
        url: 'https://xdevhub.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'xMoney',
        url: 'https://www.xmoney.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'MultiversX Wallet',
        url: 'https://wallet.multiversx.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'MultiversX Explorer',
        url: 'https://explorer.multiversx.com/',
        icon: null,
    },
    {
        category: 'official',
        name: 'xAlliance',
        url: 'https://xalliance.io/',
        icon: null,
    },
    {
        category: 'official',
        name: 'CodeMultiversX',
        url: 'https://docs.multiversx.com/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'XOXNO',
        url: 'https://xoxno.com/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'Krogan',
        url: 'https://kroganswap.com/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'Flipix',
        url: 'https://flipix.io/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'OnionX',
        url: 'https://www.ooxart.art/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'Rug Royalties',
        url: 'https://rug.divergentclub.xyz/',
        icon: null,
    },
    {
        category: 'marketplace',
        name: 'RareArt',
        url: 'https://www.rareart.app/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Hatom',
        url: 'https://www.hatom.com/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'AshSwap',
        url: 'https://ashswap.io/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'OneDex',
        url: 'https://onedex.app/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Pulsar Money',
        url: 'https://pulsar.money/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'JEX',
        url: 'https://app.jexchange.io/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Proteo',
        url: 'https://proteodefi.com/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'AshPerp',
        url: 'https://ashperp.trade/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'JewelSwap',
        url: 'https://www.jewelswap.io/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Exrond',
        url: 'https://exrond.com/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'QuantumX',
        url: 'https://www.quantumx.network/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'ENTITY',
        url: 'https://www.entity.global/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Pell Network',
        url: 'https://pell.network/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'AutoScale',
        url: 'https://autoscale.fi/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Burnify',
        url: 'https://burnify.app/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'Salsa',
        url: 'https://staking.agency/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'CoinDrip',
        url: 'https://coindrip.finance/',
        icon: null,
    },
    {
        category: 'defi',
        name: 'FunDex',
        url: 'https://fundex.fun/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'Materia Prima',
        url: 'https://play.materiaprimanft.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'Shadow Lands',
        url: 'https://dustybones.xyz/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'Knights of Cathena',
        url: 'https://knights-of-cathena.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'xAntsGame',
        url: 'https://www.antsgame.io/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'The Cursed Land',
        url: 'https://www.thecursedland.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'xArcadia',
        url: 'https://www.elrondarcadia.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'Giants',
        url: 'https://giantsvillage.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'Gods of Fire',
        url: 'https://godsoffire.io/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'World of Shrooms',
        url: 'https://x.com/WOShrooms',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'JCorp',
        url: 'https://play.jcorpbattleofgods.com/',
        icon: null,
    },
    {
        category: 'gaming',
        name: 'WAM',
        url: 'https://wam.app',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xBoard',
        url: 'https://xboard.run/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'e-Compass',
        url: 'https://e-compass.io/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xDustConverter',
        url: 'https://xdustconverter.com/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'PeerMe',
        url: 'https://peerme.io/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'MultiversX Builders',
        url: 'https://multiversxbuilders.com/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xLibrary',
        url: 'https://www.mvxlibrary.com/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xAnalyze',
        url: 'https://xanalyze.io/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'SOMA',
        url: 'https://soma.tools/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Saturn',
        url: 'https://projectx.mx/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'EDGE',
        url: 'https://projectx.mx/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Atlas',
        url: 'https://projectx.mx/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xPlore',
        url: 'https://www.xplore-multiversx.com/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Octools',
        url: 'https://octools.app/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'MvxBrand',
        url: 'https://mvxbrand.fun/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xVisualize',
        url: 'https://xvisualize.netlify.app/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Spawnable',
        url: 'https://spawnable.io/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Warps',
        url: 'https://usewarp.to/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Tagrity',
        url: 'https://tagrity.io/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'Buildo',
        url: 'https://www.buildo.dev/',
        icon: null,
    },
    {
        category: 'tool',
        name: 'xSafe',
        url: 'https://xsafe.io/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Project X',
        url: 'https://projectx.mx/',
        icon: '/logos/project-x.png',
    },
    {
        category: 'nft',
        name: 'EAPES',
        url: 'https://www.eapes.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'SRB Labs',
        url: 'https://superrarebears.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'CowCow',
        url: 'https://www.cowcow.io/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'E.V Ecosystem',
        url: 'https://dapp.eventivivi.it/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Boogas',
        url: 'https://boogas.io/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Globees',
        url: 'https://www.globees.co/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'ESTAR',
        url: 'https://estar.games/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'ICI',
        url: 'https://ici.ro',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Vapor Republic',
        url: 'https://vaporrepublic.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'SuperVictorUniverse',
        url: 'https://supervictornft.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'BAXC',
        url: 'https://x.com/BoredApeXClub',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Synth Legion',
        url: 'https://x.com/eSynths',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Divergent Club',
        url: 'https://divergentclub.framer.website/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'The Ducks',
        url: 'https://x.com/elrondducks',
        icon: null,
    },
    {
        category: 'nft',
        name: 'HODL Token Club',
        url: 'https://x.com/HodlTokenClub',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Pitzz',
        url: 'https://x.com/CryptoPittz',
        icon: null,
    },
    {
        category: 'nft',
        name: 'BLOOPX',
        url: 'https://mint-bloopx.netlify.app/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'PokerXperience',
        url: 'https://x.com/XperiencePoker',
        icon: null,
    },
    {
        category: 'nft',
        name: 'GalaticX',
        url: 'https://www.galacticxbet.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'OwlCity',
        url: 'https://x.com/OwlCitizensX',
        icon: null,
    },
    {
        category: 'nft',
        name: 'PeGo',
        url: 'https://thepego.fun/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'xSpotlight',
        url: 'https://xspotlight.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Versus Projects',
        url: 'https://x.com/VersusProjects',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Odd Apes Gang',
        url: 'https://dapp.eventivivi.it/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Elrond Buddies',
        url: 'https://www.elrondbuddies.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Monster Squad',
        url: 'https://monstersquad.io/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'DinoVox',
        url: 'https://www.dinovox.com/fr',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Salvaki',
        url: 'https://salvagames.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Mice City',
        url: 'https://micecity.club/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'xKing',
        url: 'https://www.xkingnftx.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Stramosi',
        url: 'https://www.stramosi.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'ArtCPAClub',
        url: 'https://artcpaclub.com/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'xCards',
        url: 'https://xcards.gg/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Orcas',
        url: 'https://orcas.gg/',
        icon: null,
    },
    {
        category: 'nft',
        name: 'FrugFrens',
        url: 'https://x.com/frugfrens',
        icon: null,
    },
    {
        category: 'nft',
        name: 'PepeVersX',
        url: 'https://x.com/PepeVersX',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Monkeys Supremacy',
        url: 'https://x.com/MonkeysSY',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Fightoons',
        url: 'https://monstersquad.io/fightoons',
        icon: null,
    },
    {
        category: 'nft',
        name: 'ePunks',
        url: 'https://x.com/ElrondPunks',
        icon: null,
    },
    {
        category: 'nft',
        name: 'Duckers',
        url: 'https://x.com/DUCKERSNFT',
        icon: null,
    },
    {
        category: 'nft',
        name: 'CollectionistX',
        url: 'https://thecollectionistx.com/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'MemeversX',
        url: 'https://memeversx.com/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'Bober',
        url: 'https://boberonmvx.com/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'BOD',
        url: 'https://bod.gg/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'MemeXchange',
        url: 'https://memexchange.fun/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'TOM',
        url: 'https://www.tomcoin.wtf/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'MxDOGE',
        url: 'https://x.com/_mxdoge',
        icon: null,
    },
    {
        category: 'meme',
        name: 'KWAK',
        url: 'https://www.kwak.lol/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'FRED',
        url: 'https://x.com/FREDONMVX',
        icon: null,
    },
    {
        category: 'meme',
        name: 'Blazzord',
        url: 'https://x.com/BlazzordNFT',
        icon: null,
    },
    {
        category: 'meme',
        name: 'Doctor X',
        url: 'https://doctorx.meme/',
        icon: null,
    },
    {
        category: 'meme',
        name: 'MINCU',
        url: 'https://x.com/OfficialMINCU',
        icon: null,
    },
    {
        category: 'ai',
        name: 'AI Nexus',
        url: 'https://www.ainexus.ltd/',
        icon: null,
    },
    {
        category: 'ai',
        name: 'JoAI',
        url: 'https://joai.ai',
        icon: null,
    },
    {
        category: 'ai',
        name: 'MakeX',
        url: 'https://x.com/MakeX_web3',
        icon: null,
    },
    {
        category: 'ai',
        name: 'AI Angels',
        url: null,
        icon: null,
    },
    {
        category: 'ai',
        name: 'FOXSY',
        url: 'https://foxsy.ai/',
        icon: null,
    },
    {
        category: 'ai',
        name: 'MvX Lib',
        url: 'https://mvxlib.vercel.app/',
        icon: null,
    },
    {
        category: 'ai',
        name: 'NPC',
        url: 'https://dorahacks.io/buidl/24069',
        icon: null,
    },
    {
        category: 'ai',
        name: 'xPilot',
        url: 'https://x.com/xPilotAI',
        icon: null,
    },
    {
        category: 'ai',
        name: 'CyBreed',
        url: 'https://www.cybreed.ai/',
        icon: null,
    },
    {
        category: 'ai',
        name: 'Tikaw AI',
        url: 'https://x.com/TikawMvx',
        icon: null,
    },
    {
        category: 'ai',
        name: 'Zaya AI',
        url: 'https://www.zaya.ai/',
        icon: null,
    },
    {
        category: 'ai',
        name: 'Laika',
        url: 'https://x.com/l_ai_ka',
        icon: null,
    },
    {
        category: 'ai',
        name: 'HiveX',
        url: 'https://hivex-ruby.vercel.app/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'QoWatt',
        url: 'https://qowatt.network/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'BHero',
        url: 'https://bhero.com/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Itheum',
        url: 'https://www.itheum.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'GoCharge Tech',
        url: 'https://gocharge.tech/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'INSPIR3',
        url: 'https://www.inspir3.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Brand Minds',
        url: 'https://brandminds.com/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'VeroPay',
        url: 'https://vero.ro/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'xAudits',
        url: 'https://xaudits.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Evoload',
        url: 'https://evoload.co/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'DIXID',
        url: 'https://dixid.ro/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'xOMG.ro',
        url: 'https://xomg.ro/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'TADA',
        url: 'https://ta-da.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Ofero',
        url: 'https://ofero.network/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'OneTap',
        url: 'https://www.onetap.design/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Cryptool.io',
        url: 'https://cryptool.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Philanthrify',
        url: 'https://philanthrify.co.uk/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Valoro',
        url: 'https://valoro.fund/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Shelters',
        url: 'https://www.shelters.finance/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'Build21',
        url: 'https://build21.io/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'NFT Social Club',
        url: 'https://multiversx.nft-social.club/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'OnChainSmokers',
        url: 'https://www.onchainsmokers.com/',
        icon: null,
    },
    {
        category: 'startup',
        name: 'HYME',
        url: null,
        icon: null,
    },
    {
        category: 'development',
        name: 'Gaupa Labs',
        url: 'https://gaupalabs.com/',
        icon: null,
    },
    {
        category: 'development',
        name: 'Buildly',
        url: 'https://www.buildly.io/',
        icon: null,
    },
    {
        category: 'development',
        name: 'Rather Labs',
        url: 'https://www.ratherlabs.com/',
        icon: null,
    },
    {
        category: 'development',
        name: 'Lucky Birds Labs',
        url: 'https://x.com/luckybirdslabs',
        icon: null,
    },
    {
        category: 'development',
        name: 'BlastAPI',
        url: 'https://blastapi.io/',
        icon: null,
    },
    {
        category: 'development',
        name: 'Arda',
        url: 'https://arda.co/',
        icon: null,
    },
    {
        category: 'media',
        name: 'GM MvX',
        url: 'https://x.com/GMWeb3_tv',
        icon: null,
    },
    {
        category: 'media',
        name: 'xSpaces',
        url: 'https://x.com/xSpac3s',
        icon: null,
    },
    {
        category: 'media',
        name: 'FullShard Podcast',
        url: 'https://fullshardpodcast.com/',
        icon: null,
    },
    {
        category: 'media',
        name: 'Momentum',
        url: 'https://www.youtube.com/playlist?list=PLQVcheGWwBRVIDczUGjpx60NDfBEWl7xh',
        icon: null,
    },
    {
        category: 'media',
        name: 'xCities',
        url: 'https://x.com/xCitiesEvent',
        icon: null,
    },
    {
        category: 'staking',
        name: 'BOBER',
        url: 'https://boberonmvx.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/bober/icon.png',
    },
    {
        category: 'staking',
        name: '01node',
        url: 'https://01node.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/01node/icon.png',
    },
    {
        category: 'staking',
        name: 'ARC Stake',
        url: 'https://arcstake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/arcstake/icon.png',
    },
    {
        category: 'staking',
        name: 'Alchemist Stake',
        url: 'https://alchemiststake.xyz/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/alchemiststakexyz/icon.png',
    },
    {
        category: 'staking',
        name: 'Alchemy',
        url: 'https://www.alchemy.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/Alchemy/icon.png',
    },
    {
        category: 'staking',
        name: 'Alchemy Capital',
        url: 'https://alchemy.capital',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/alchemycapital/icon.png',
    },
    {
        category: 'staking',
        name: 'AllStar-Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/allstar-staking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'AlpineSafe Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/alpinesafestaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Animoca Brands NAAS',
        url: 'https://www.animocabrands.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/animocabrandsnaas/icon.png',
    },
    {
        category: 'staking',
        name: 'ApeStaking',
        url: 'https://apestaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/apestaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Aurentum GmbH',
        url: 'https://www.aurentum-finance.de',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/aurentum/icon.png',
    },
    {
        category: 'staking',
        name: 'Binance Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/binance_staking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Buidly Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/galaxyone/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Carpathian Stake',
        url: 'https://carpathianstake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/carpathianstake/icon.png',
    },
    {
        category: 'staking',
        name: 'CastleStake.com',
        url: 'https://www.castlestake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/castlestake/icon.png',
    },
    {
        category: 'staking',
        name: 'Cavaleria Staking',
        url: 'https://staking.cavaleria.ro/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/cavaleriastaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Chain State Labs',
        url: 'https://cslabs.io',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/cslabsio/icon.png',
    },
    {
        category: 'staking',
        name: 'Christstake',
        url: 'https://christstake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/christstake/icon.png',
    },
    {
        category: 'staking',
        name: 'Colombia Staking',
        url: 'https://colombia-staking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/colombiastaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Core Block',
        url: 'https://coreblock.cloud',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/core-block/icon.png',
    },
    {
        category: 'staking',
        name: 'CryptoBay',
        url: 'https://cryptobay.space',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/cryptobayspace/icon.png',
    },
    {
        category: 'staking',
        name: 'CryptoShiGo',
        url: 'https://tools.multiversx.com/assets-cdn/identities/cryptoshigo/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'D1fferent Capital',
        url: 'https://d1fferent.capital/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/d1fferentcapital/icon.png',
    },
    {
        category: 'staking',
        name: 'Dappmed Poland',
        url: 'https://tools.multiversx.com/assets-cdn/identities/imsm/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Deutsche Telekom Staking',
        url: 'https://geschaeftskunden.telekom.de/digitale-loesungen/infrastructure-as-a-service/staking-en',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/staking-vaas/icon.png',
    },
    {
        category: 'staking',
        name: 'EAPES Validator',
        url: 'https://eapesvalidator.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/eapesvalidator/icon.png',
    },
    {
        category: 'staking',
        name: 'EGLDSqueeze',
        url: 'https://tools.multiversx.com/assets-cdn/identities/egldsqueeze/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Easy 2 Stake',
        url: 'https://easy2stake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/easy2stake/icon.png',
    },
    {
        category: 'staking',
        name: 'Eda',
        url: 'https://tools.multiversx.com/assets-cdn/identities/kevinlallement/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Egld Staking Provider 🎖',
        url: 'https://egldstakingprovider.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/egldstakingprovider/icon.png',
    },
    {
        category: 'staking',
        name: 'Elrond Philippines Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/zillabytes/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'EndeavorStaking',
        url: 'https://endeavorstaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/endeavorstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Entity',
        url: 'https://entity.global',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/enttechnologies/icon.png',
    },
    {
        category: 'staking',
        name: 'Equilibrium',
        url: 'https://tools.multiversx.com/assets-cdn/identities/equilibrium/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Equinoxe Capital',
        url: 'https://tools.multiversx.com/assets-cdn/identities/equinoxecapital/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Everstake',
        url: 'https://everstake.one',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/everstake/icon.png',
    },
    {
        category: 'staking',
        name: 'ExceptionLabs',
        url: 'https://exceptionlabs.net',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/exceptionlabs/icon.png',
    },
    {
        category: 'staking',
        name: 'Fellowship Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/fellowship-staking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Figment',
        url: 'https://figment.io',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/figment-networks/icon.png',
    },
    {
        category: 'staking',
        name: 'Forbole',
        url: 'https://forbole.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/forbole/icon.png',
    },
    {
        category: 'staking',
        name: 'FourtyTwo',
        url: 'https://fourtytwo.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/fourtytwoag/icon.png',
    },
    {
        category: 'staking',
        name: 'Foxsy AI',
        url: 'https://foxsy.ai',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/oxsyai/icon.png',
    },
    {
        category: 'staking',
        name: 'FriendsStaking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/friendsstaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Helios Staking',
        url: 'https://heliosstaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/heliosstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Hyperblocks Pro',
        url: 'https://hyperblocks.pro/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/hyperblockspro/icon.png',
    },
    {
        category: 'staking',
        name: 'Ieleman',
        url: 'https://ieleman.ro/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/ieleman/icon.png',
    },
    {
        category: 'staking',
        name: 'ImpactStaking',
        url: 'https://impactstaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/impactstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Incal 2025',
        url: 'https://incal.noweb',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/incalng/icon.png',
    },
    {
        category: 'staking',
        name: 'Inception Network',
        url: 'https://inception-network.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/inceptionnetwork/icon.png',
    },
    {
        category: 'staking',
        name: 'InfStones',
        url: 'https://tools.multiversx.com/assets-cdn/identities/infstonescom/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Inotel',
        url: 'https://inotel.ro',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/inotel/icon.png',
    },
    {
        category: 'staking',
        name: 'Kiln',
        url: 'https://kiln.fi',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/kilnfi/icon.png',
    },
    {
        category: 'staking',
        name: 'KryptoDots️',
        url: 'https://kryptodots.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/kryptodots/icon.png',
    },
    {
        category: 'staking',
        name: 'Ledger by Figment',
        url: 'https://figment.io',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/ledgerbyfigment/icon.png',
    },
    {
        category: 'staking',
        name: 'Lion Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/lionstaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Luganodes',
        url: 'https://luganodes.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/luganodes/icon.png',
    },
    {
        category: 'staking',
        name: 'MGStaking',
        url: 'https://MGStaking.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/mgstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Maple Leaf Network',
        url: 'https://tools.multiversx.com/assets-cdn/identities/mapleleafnetwork/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Mash',
        url: 'https://tools.multiversx.com/assets-cdn/identities/marbaldur/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Meria',
        url: 'https://meria.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/meria/icon.png',
    },
    {
        category: 'staking',
        name: 'Metropolis',
        url: 'https://www.metropolistaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/Metropolis/icon.png',
    },
    {
        category: 'staking',
        name: 'Middle Staking',
        url: 'https://www.middlestaking.fr/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/middlestaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Moonlorian Stake',
        url: 'https://t.me/moonlorian',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/moonlorianstake/icon.png',
    },
    {
        category: 'staking',
        name: 'Mr.Reboot',
        url: 'https://tools.multiversx.com/assets-cdn/identities/newstake/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'MultiversX Community Delegation 🎖',
        url: 'https://multiversx.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/multiversx/icon.png',
    },
    {
        category: 'staking',
        name: 'NTH Inc',
        url: 'https://nthinc.ro',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/nethus/icon.png',
    },
    {
        category: 'staking',
        name: 'New Age Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/n_a_s/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Nic Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/nictherick/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Ninja Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/ninjastaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Octopos',
        url: 'https://multiversx.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/octopos/icon.png',
    },
    {
        category: 'staking',
        name: 'Ofero Staking',
        url: 'https://ofero.network',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/oferostaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Orange Staking',
        url: 'www.orangestaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/orangestaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Orius International',
        url: 'https://twitter.com/OriusLLC',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/orius/icon.png',
    },
    {
        category: 'staking',
        name: 'OwlHero',
        url: 'https://tools.multiversx.com/assets-cdn/identities/owlhero/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'P2P Validator',
        url: 'https://p2p.org',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/p2p_org_/icon.png',
    },
    {
        category: 'staking',
        name: 'PartnerStaking',
        url: 'https://partnerstaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/partnerstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Peacock Validator',
        url: 'https://tools.multiversx.com/assets-cdn/identities/peacockvalidator/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'PhiDelta Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/phidelta/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Primal Block One',
        url: 'https://primalblock.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/primal-block-one/icon.png',
    },
    {
        category: 'staking',
        name: 'Primal Block Two',
        url: 'https://primalblock.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/primal-block-two/icon.png',
    },
    {
        category: 'staking',
        name: 'Prime Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/primestaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'ProCrypto Distributed Staking',
        url: 'https://pc.io',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/procryptostaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Pulsar Money',
        url: 'https://tools.multiversx.com/assets-cdn/identities/pulsarmoney/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Raf Staking',
        url: 'https://www.rafstaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/rafstakeagency/icon.png',
    },
    {
        category: 'staking',
        name: 'Rarity.market NFT marketplace',
        url: 'https://rarity.market',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/rarity-market/icon.png',
    },
    {
        category: 'staking',
        name: 'Restake',
        url: 'https://restake.net',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/restake/icon.png',
    },
    {
        category: 'staking',
        name: 'Risa Staking',
        url: 'https://risastaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/risasoft/icon.png',
    },
    {
        category: 'staking',
        name: 'RockX',
        url: 'https://tools.multiversx.com/assets-cdn/identities/rockxrocks/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'RosettaStake',
        url: 'https://rosettastake.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/rosettastake/icon.png',
    },
    {
        category: 'staking',
        name: 'Runtime Verification',
        url: 'https://runtimeverification.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/rvstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Shire Staking',
        url: 'https://multiversx.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/omni1979/icon.png',
    },
    {
        category: 'staking',
        name: 'Sikka',
        url: 'https://sikka.tech',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/sikka_tech/icon.png',
    },
    {
        category: 'staking',
        name: 'Sky Soft Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/skysoft/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'SmartChainConnection',
        url: 'https://smartchainconnection.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/smartchainconnection/icon.png',
    },
    {
        category: 'staking',
        name: 'Stake Capital Group (validators)',
        url: 'https://www.stake.capital/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/stakedao-devops/icon.png',
    },
    {
        category: 'staking',
        name: 'Stake X',
        url: 'https://tools.multiversx.com/assets-cdn/identities/stake_x/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Stake-o-Matic',
        url: 'https://stake-o-matic.io',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/stakeomatic/icon.png',
    },
    {
        category: 'staking',
        name: 'Stake24',
        url: 'https://tools.multiversx.com/assets-cdn/identities/stake24/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'StakeCON',
        url: 'https://stakecon.ro',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/stakecon/icon.png',
    },
    {
        category: 'staking',
        name: 'StakeM',
        url: 'https://explorer.multiversx.com/validators',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/StakeM/icon.png',
    },
    {
        category: 'staking',
        name: 'StakeUP',
        url: 'https://explorer.multiversx.com/validators',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/StakeUP/icon.png',
    },
    {
        category: 'staking',
        name: 'Staking Agency',
        url: 'https://staking.agency',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/stakingagency/icon.png',
    },
    {
        category: 'staking',
        name: 'Staking4All',
        url: 'https://www.staking4all.org/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/staking4all/icon.png',
    },
    {
        category: 'staking',
        name: 'Star Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/star_staking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Swigs Staking',
        url: 'https://www.swigs.ch',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/swigsstaking/icon.png',
    },
    {
        category: 'staking',
        name: 'SyncNode',
        url: 'https://tools.multiversx.com/assets-cdn/identities/gbunea/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'SyndicateX Staking',
        url: 'https://syndicatemvx.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/syndicatex/icon.png',
    },
    {
        category: 'staking',
        name: 'Synexis',
        url: 'https://github.com/synexis',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/Synexis/icon.png',
    },
    {
        category: 'staking',
        name: 'The Palm Tree Network',
        url: 'https://thepalmtree.network/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/thepalmtreenw/icon.png',
    },
    {
        category: 'staking',
        name: 'TheTransylvanianTrader',
        url: 'https://linktr.ee/ttt_mvx_thetransylvaniantrader',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/ttt-thetransylvaniantrader/icon.png',
    },
    {
        category: 'staking',
        name: 'TitanStake',
        url: 'https://www.titanstake.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/titanstake/icon.png',
    },
    {
        category: 'staking',
        name: 'Tomato',
        url: 'https://tools.multiversx.com/assets-cdn/identities/tomato/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Tortuga Staking',
        url: 'https://tortuga-staking.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/tortugastaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Transylvania Staking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/trstaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Trust Staking',
        url: 'https://truststaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/truststaking/icon.png',
    },
    {
        category: 'staking',
        name: 'Trust Staking Netherlands',
        url: 'https://truststaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/truststakingne/icon.png',
    },
    {
        category: 'staking',
        name: 'Trust Staking Switzerland',
        url: 'https://truststaking.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/truststakingsw/icon.png',
    },
    {
        category: 'staking',
        name: 'Trust Wallet',
        url: 'https://trustwallet.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/trustwallet/icon.png',
    },
    {
        category: 'staking',
        name: 'UnitedGroupCapital',
        url: 'https://unitedgroup.capital/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/unitedgroupcapital/icon.png',
    },
    {
        category: 'staking',
        name: 'Valid Blocks',
        url: 'https://validblocks.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/validblocks/icon.png',
    },
    {
        category: 'staking',
        name: 'Valuestaking',
        url: 'https://tools.multiversx.com/assets-cdn/identities/valuestaking/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Vapor Republic',
        url: 'https://www.vaporrepublic.com/',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/vaporrepublic/icon.png',
    },
    {
        category: 'staking',
        name: 'Wavenode | eDIA AirDrops',
        url: 'https://x.com/WavenodeAgent',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/wavenodevalidat/icon.png',
    },
    {
        category: 'staking',
        name: 'WeHaveServers.com',
        url: 'https://tools.multiversx.com/assets-cdn/identities/wehaveservers/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'WeStake',
        url: 'https://tools.multiversx.com/assets-cdn/identities/westake/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'XOXNO',
        url: 'https://xoxno.com',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/xoxno/icon.png',
    },
    {
        category: 'staking',
        name: 'art3mis.cloud',
        url: 'https://art3mis.cloud',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/art3mis/icon.png',
    },
    {
        category: 'staking',
        name: 'iVerse Vision',
        url: 'https://iverse.vision',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/istariv/icon.png',
    },
    {
        category: 'staking',
        name: 'stakeGEN',
        url: 'https://tools.multiversx.com/assets-cdn/identities/stakegen/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'stakecamp',
        url: 'https://tools.multiversx.com/assets-cdn/identities/stakecamp/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'steak4all',
        url: 'https://tools.multiversx.com/assets-cdn/identities/steak4all/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: 'Disruptive Digital',
        url: 'https://disruptivedigital.eu',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/disruptivedigital/icon.png',
    },
    {
        category: 'staking',
        name: 'Chief Engineer Staking',
        url: 'https://t.me/chiefengineerstaking',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/chiefeng/icon.png',
    },
    {
        category: 'staking',
        name: 'nose-TRACTION-baltic',
        url: 'https://tools.multiversx.com/assets-cdn/identities/nosetraction/icon.png',
        icon: null,
    },
    {
        category: 'staking',
        name: '0% fee + monthly aidrop $WATER Works',
        url: 'https://twitter.com/Web3Water',
        icon: 'https://tools.multiversx.com/assets-cdn/identities/web3water/icon.png',
    },
];
